export default function Gallery() {
  return (
    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold text-gray-900 sm:text-4xl">
          Image Gallery
        </h1>
        <p className="mt-4 text-lg text-gray-600">
          Browse and explore images generated by our AI models
        </p>
      </div>
      
      <div className="gallery-grid">
        {/* Placeholder images */}
        {Array.from({ length: 8 }).map((_, i) => (
          <div key={i} className="card hover-lift">
            <div className="aspect-square bg-gray-100 rounded-lg flex items-center justify-center">
              <p className="text-gray-500">Generated Image {i + 1}</p>
            </div>
            <div className="p-4">
              <p className="text-sm text-gray-600">Sample prompt description</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}